[package]
name = "mint"
version = "0.1.0"
edition = "2021"
# resolver = "2" #https://doc.rust-lang.org/beta/cargo/reference/features.html#feature-resolver-version-2

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.11.4"
# spl-token-2022 = "0.4.2"
spl-token = { version = "3.3.0", features = ["no-entrypoint"]}
spl-associated-token-account = { version = "1.0.5", features = ["no-entrypoint"]}
# ERROR with getrandom package when building with cargo build-bpf
# https://users.rust-lang.org/t/use-of-undeclared-crate-or-module-imp-on-getrandom-0-2-3-when-building-for-wasm32-unknown-unknown/70171
# getrandom = { version = "0.2", features = ["js"]} 

[dev-dependencies]
solana-program-test = "1.11.4"
solana-sdk = "1.11.4"

[lib]
crate-type = ["cdylib", "lib"]